./run_test_state.sh dialogue_splits_contextsize2_v2_state_medium_$1neg/ 10 medium do_not_like_earlier_show_result $1
./run_test_state.sh dialogue_splits_contextsize2_v2_state_medium_$1neg/ 10 medium do_not_like_n_show_result $1
./run_test_state.sh dialogue_splits_contextsize2_v2_state_medium_$1neg/ 10 medium do_not_like_show_result $1
./run_test_state.sh dialogue_splits_contextsize2_v2_state_medium_$1neg/ 10 medium filter_results $1
./run_test_state.sh dialogue_splits_contextsize2_v2_state_medium_$1neg/ 10 medium like_earlier_show_result $1
./run_test_state.sh dialogue_splits_contextsize2_v2_state_medium_$1neg/ 10 medium like_n_show_result $1
./run_test_state.sh dialogue_splits_contextsize2_v2_state_medium_$1neg/ 10 medium like_show_result $1
./run_test_state.sh dialogue_splits_contextsize2_v2_state_medium_$1neg/ 10 medium show_orientation $1
./run_test_state.sh dialogue_splits_contextsize2_v2_state_medium_$1neg/ 10 medium show_similar_to $1
./run_test_state.sh dialogue_splits_contextsize2_v2_state_medium_$1neg/ 10 medium sort_results $1

#./run_test_state.sh dialogue_splits_contextsize2_state_medium_$1neg/ 10 medium do_not_like_earlier_show_result $1
#./run_test_state.sh dialogue_splits_contextsize2_state_medium_$1neg/ 10 medium do_not_like_n_show_result $1
#./run_test_state.sh dialogue_splits_contextsize2_state_medium_$1neg/ 10 medium do_not_like_show_result $1
#./run_test_state.sh dialogue_splits_contextsize2_state_medium_$1neg/ 10 medium filter_results $1
#./run_test_state.sh dialogue_splits_contextsize2_state_medium_$1neg/ 10 medium like_earlier_show_result $1
#./run_test_state.sh dialogue_splits_contextsize2_state_medium_$1neg/ 10 medium like_n_show_result $1
#./run_test_state.sh dialogue_splits_contextsize2_state_medium_$1neg/ 10 medium like_show_result $1
#./run_test_state.sh dialogue_splits_contextsize2_state_medium_$1neg/ 10 medium show_orientation $1
#./run_test_state.sh dialogue_splits_contextsize2_state_medium_$1neg/ 10 medium show_similar_to $1
#./run_test_state.sh dialogue_splits_contextsize2_state_medium_$1neg/ 10 medium sort_results $1
