#cp params_test_v1.py params_test.py
#./run_test_state.sh dialogue_splits_contextsize2_copy do_not_like_earlier_show_result
#./run_test_state.sh dialogue_splits_contextsize2_copy do_not_like_n_show_result
#./run_test_state.sh dialogue_splits_contextsize2_copy do_not_like_show_result
#./run_test_state.sh dialogue_splits_contextsize2_copy filter_results
#./run_test_state.sh dialogue_splits_contextsize2_copy like_earlier_show_result
#./run_test_state.sh dialogue_splits_contextsize2_copy like_n_show_result
#./run_test_state.sh dialogue_splits_contextsize2_copy like_show_result
#./run_test_state.sh dialogue_splits_contextsize2_copy show_orientation
#./run_test_state.sh dialogue_splits_contextsize2_copy show_similar_to
#./run_test_state.sh dialogue_splits_contextsize2_copy sort_results

#./run_test_state.sh dialogue_splits_contextsize2_copy show_result
#./run_test_state.sh dialogue_splits_contextsize2_copy go_with
#./run_test_state.sh dialogue_splits_contextsize2_copy ask_attribute
#./run_test_state.sh dialogue_splits_contextsize2_copy celebrity
#./run_test_state.sh dialogue_splits_contextsize2_copy buy
#./run_test_state.sh dialogue_splits_contextsize2_copy suited_for

cp params_test_v2.py params_test.py
#./run_test_state.sh dialogue_splits_contextsize2_v2 do_not_like_earlier_show_result
#./run_test_state.sh dialogue_splits_contextsize2_v2 do_not_like_n_show_result
#./run_test_state.sh dialogue_splits_contextsize2_v2 do_not_like_show_result
#./run_test_state.sh dialogue_splits_contextsize2_v2 filter_results
#./run_test_state.sh dialogue_splits_contextsize2_v2 like_earlier_show_result
#./run_test_state.sh dialogue_splits_contextsize2_v2 like_n_show_result
#./run_test_state.sh dialogue_splits_contextsize2_v2 like_show_result
#./run_test_state.sh dialogue_splits_contextsize2_v2 show_orientation
#./run_test_state.sh dialogue_splits_contextsize2_v2 show_similar_to
#./run_test_state.sh dialogue_splits_contextsize2_v2 sort_results

./run_test_state.sh dialogue_splits_contextsize2_v2 show_result
./run_test_state.sh dialogue_splits_contextsize2_v2 go_with
./run_test_state.sh dialogue_splits_contextsize2_v2 ask_attribute
./run_test_state.sh dialogue_splits_contextsize2_v2 celebrity
./run_test_state.sh dialogue_splits_contextsize2_v2 buy
./run_test_state.sh dialogue_splits_contextsize2_v2 suited_for
